Repository wirecard/magento-ee, pull requests merged in 2020-02, with the labels that each got.

#120 Tpwdcee 5974 - whitelisted support fields
  lib/WirecardEE/PaymentGateway/Mail/SupportMail.php
Labels: ready for review

#121 Update prlint.json
  .github/prlint.json
Labels: no-release

#122 Disable nightly compatibility checks
  .travis.yml
Labels: no-release, ready for approval

#119 RC-2.0.1
  CHANGELOG.md
  SHOPVERSIONS
  app/code/community/WirecardEE/PaymentGateway/etc/config.xml
  lib/WirecardEE/PaymentGateway/Mail/SupportMail.php
Labels: patch

#123 Remove unrelevant badges
  README.md
Labels: no-release

#124 Add new credentials and improve PayPal test
  tests/Selenium/Payments/PayPalTest.js
  tests/Selenium/config.js
Labels: no-release, ready for approval
